#!/bin/bash

cd data
mkdir coco
cd coco
wget "http://images.cocodataset.org/annotations/annotations_trainval2014.zip"
unzip annotations_trainval2014.zip
mkdir images
cd images
wget "http://images.cocodataset.org/zips/train2014.zip"
wget "http://images.cocodataset.org/zips/val2014.zip"
unzip val2014.zip
unzip train2014.zip
rm train2014.zip
rm val2014.zip
cd ..
cp annotations/instances_val2014.json annotations/image_info_minival2014.json
rm annotations_trainval2014.zip
cd ..
wget "http://datasets.d2.mpi-inf.mpg.de/hosang17cvpr/coco_2014_FRCN.tar.gz"
tar xf coco_2014_FRCN.tar.gz
rm coco_2014_FRCN.tar.gz
cd ..
git clone https://github.com/cocodataset/cocoapi.git
cd cocoapi/PythonAPI
make
python setup.py install
